// <auto-generated />
using System;
using Infrastructure.Adapters.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Adapters.Postgres.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.OsagoAggregate.ExpiryStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("expiry_status", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "notexpired"
                        },
                        new
                        {
                            Id = 2,
                            Name = "expired"
                        });
                });

            modelBuilder.Entity("Domain.OsagoAggregate.Osago", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("DateOfExpiry")
                        .HasColumnType("date")
                        .HasColumnName("date_of_expiry");

                    b.Property<DateOnly>("DateOfIssue")
                        .HasColumnType("date")
                        .HasColumnName("date_of_issue");

                    b.Property<string>("PhotoStorageBucketAndKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("photo_storage_bucket_and_key");

                    b.Property<Guid>("VehicleDocumentsId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_documents_id");

                    b.Property<int>("expiry_status_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VehicleDocumentsId");

                    b.HasIndex("expiry_status_id");

                    b.ToTable("osago", (string)null);
                });

            modelBuilder.Entity("Domain.VehicleDocumentsAggregate.VehicleDocuments", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.ToTable("vehicle_documents", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Adapters.Postgres.Inbox.InboxEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("EventId");

                    b.HasIndex(new[] { "OccurredOnUtc", "ProcessedOnUtc" }, "IX_inbox_messages_unprocessed")
                        .HasFilter("processed_on_utc IS NULL");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex(new[] { "OccurredOnUtc", "ProcessedOnUtc" }, "IX_inbox_messages_unprocessed"), new[] { "EventId", "Type" });

                    b.ToTable("inbox", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Adapters.Postgres.Outbox.OutboxEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("EventId");

                    b.HasIndex(new[] { "OccurredOnUtc", "ProcessedOnUtc" }, "IX_outbox_messages_unprocessed")
                        .HasFilter("processed_on_utc IS NULL");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex(new[] { "OccurredOnUtc", "ProcessedOnUtc" }, "IX_outbox_messages_unprocessed"), new[] { "EventId", "Type" });

                    b.ToTable("outbox", (string)null);
                });

            modelBuilder.Entity("Domain.OsagoAggregate.Osago", b =>
                {
                    b.HasOne("Domain.VehicleDocumentsAggregate.VehicleDocuments", null)
                        .WithMany()
                        .HasForeignKey("VehicleDocumentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_vehicle_documents");

                    b.HasOne("Domain.OsagoAggregate.ExpiryStatus", "ExpiryStatus")
                        .WithMany()
                        .HasForeignKey("expiry_status_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_expiry_status_id");

                    b.Navigation("ExpiryStatus");
                });

            modelBuilder.Entity("Domain.VehicleDocumentsAggregate.VehicleDocuments", b =>
                {
                    b.OwnsOne("Domain.SharedKernel.ValueObjects.Pts", "Pts", b1 =>
                        {
                            b1.Property<Guid>("VehicleDocumentsId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BackPhotoStorageBucketAndKey")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("pts_back_photo_storage_bucket_and_key");

                            b1.Property<string>("FrontPhotoStorageBucketAndKey")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("pts_front_photo_storage_bucket_and_key");

                            b1.Property<DateOnly>("YearOfManufacture")
                                .HasColumnType("date")
                                .HasColumnName("pts_year_of_manufacture");

                            b1.HasKey("VehicleDocumentsId");

                            b1.ToTable("vehicle_documents");

                            b1.WithOwner()
                                .HasForeignKey("VehicleDocumentsId");

                            b1.OwnsOne("Domain.SharedKernel.ValueObjects.Color", "Color", b2 =>
                                {
                                    b2.Property<Guid>("PtsVehicleDocumentsId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("pts_color");

                                    b2.HasKey("PtsVehicleDocumentsId");

                                    b2.ToTable("vehicle_documents");

                                    b2.WithOwner()
                                        .HasForeignKey("PtsVehicleDocumentsId");
                                });

                            b1.OwnsOne("Domain.SharedKernel.ValueObjects.Vin", "Vin", b2 =>
                                {
                                    b2.Property<Guid>("PtsVehicleDocumentsId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Number")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("pts_vin");

                                    b2.HasKey("PtsVehicleDocumentsId");

                                    b2.ToTable("vehicle_documents");

                                    b2.WithOwner()
                                        .HasForeignKey("PtsVehicleDocumentsId");
                                });

                            b1.Navigation("Color")
                                .IsRequired();

                            b1.Navigation("Vin")
                                .IsRequired();
                        });

                    b.OwnsOne("Domain.SharedKernel.ValueObjects.Sts", "Sts", b1 =>
                        {
                            b1.Property<Guid>("VehicleDocumentsId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BackPhotoStorageBucketAndKey")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("sts_back_photo_storage_bucket_and_key");

                            b1.Property<string>("FrontPhotoStorageBucketAndKey")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("sts_front_photo_storage_bucket_and_key");

                            b1.HasKey("VehicleDocumentsId");

                            b1.ToTable("vehicle_documents");

                            b1.WithOwner()
                                .HasForeignKey("VehicleDocumentsId");
                        });

                    b.OwnsOne("Domain.VehicleDocumentsAggregate.Status", "Status", b1 =>
                        {
                            b1.Property<Guid>("VehicleDocumentsId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsOsagoAdded")
                                .HasColumnType("boolean")
                                .HasColumnName("is_osago_added");

                            b1.Property<bool>("IsPtsAdded")
                                .HasColumnType("boolean")
                                .HasColumnName("is_pts_added");

                            b1.Property<bool>("IsStsAdded")
                                .HasColumnType("boolean")
                                .HasColumnName("is_sts_added");

                            b1.HasKey("VehicleDocumentsId");

                            b1.ToTable("vehicle_documents");

                            b1.WithOwner()
                                .HasForeignKey("VehicleDocumentsId");
                        });

                    b.Navigation("Pts");

                    b.Navigation("Status")
                        .IsRequired();

                    b.Navigation("Sts");
                });
#pragma warning restore 612, 618
        }
    }
}
